/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.text.DecimalFormat;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Pablo Rey
 */
public class PanelReservaCompletada extends javax.swing.JPanel {

    /**
     * Creates new form PanelInicial
     */
    private Ventana v;
    private Timer t;
    private DatosReserva d;
    DecimalFormat formato;     
    
    private final ImageIcon iconoAudioOn;
    private final ImageIcon iconoAudioOff;
    URL urlAudioOn = PanelReservaCompletada.class.getResource("/img/audioOn.png");
    URL urlAudioOff = PanelReservaCompletada.class.getResource("/img/audioOff.png");
    boolean clicked = true;    
    
    public Ventana getV() {
        return v;
    }

    public void setV(Ventana v) {
        this.v = v;
    }
    
    public PanelReservaCompletada(DatosReserva d) {
        initComponents();
        
        // Declaramos las variables para los iconos de los altavoces
        // e iniciamos el contador de tiempo de inactividad
        iconoAudioOn = new javax.swing.ImageIcon(urlAudioOn);
                iconoAudioOff = new javax.swing.ImageIcon(urlAudioOff);        
        
        int tiempoEspera = 4 * 60 * 1000;
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                v.getContentPane().setVisible(false);
                PanelInactive pi = new PanelInactive(d);
                pi.setVisible(true);
                pi.setV(v);
                v.setContentPane(pi);                 
            }
        };
        t = new Timer(tiempoEspera, taskPerformer);
        t.start();       
        formato = new DecimalFormat("0.00");
        
        if(d != null) {
            this.d = d;
        }
        
        HashMap<Participante, Actividade> a = d.getActividades();
        if(a != null) {   
            float total = 0;
            int i = 0;
            for(HashMap.Entry<Participante, Actividade> entrada : a.entrySet()){
                if(i == 0) {
                    campoData.setText(entrada.getValue().getData());
                    campoParticipante1.setText(entrada.getKey().getNome() + " con DNI " + entrada.getKey().getDni());
                    campoImporte1.setText(entrada.getValue().getDescricion() + " ->      " + formato.format(entrada.getValue().getPrezo()) + " €");
                    total += entrada.getValue().getPrezo();
                    i++;
                } else if(i == 1) {
                    campoParticipante2.setText(entrada.getKey().getNome() + " con DNI " + entrada.getKey().getDni());
                    campoImporte2.setText(entrada.getValue().getDescricion() + " ->      " + formato.format(entrada.getValue().getPrezo()) + " €");
                    total += entrada.getValue().getPrezo();                    
                    i++;                    
                } else {
                    break;
                }
            }
            campoImporteTotal.setText(formato.format(total) + "€ ");
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        audioOn = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        botonHome = new javax.swing.JLabel();
        botonPower = new javax.swing.JLabel();
        botonAtras = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonFinalizar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        campoData = new javax.swing.JTextField();
        campoParticipante1 = new javax.swing.JTextField();
        campoParticipante2 = new javax.swing.JTextField();
        campoImporte2 = new javax.swing.JTextField();
        campoImporteTotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        campoImporte1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setMaximumSize(new java.awt.Dimension(1280, 800));
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setPreferredSize(new java.awt.Dimension(1280, 800));

        audioOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/audioOn.png"))); // NOI18N
        audioOn.setToolTipText("Activa o desactiva la asistencia por voz");
        audioOn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        audioOn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                audioOnMouseClicked(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });

        botonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        botonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonHomeMouseClicked(evt);
            }
        });

        botonPower.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/power.png"))); // NOI18N
        botonPower.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPowerMouseClicked(evt);
            }
        });

        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return.png"))); // NOI18N
        botonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAtrasMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(153, 153, 255));
        jLabel2.setFont(new java.awt.Font("TimeBurner", 0, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("martes 15 de novembro de 2016, 13:45");

        jComboBox1.setBackground(new java.awt.Color(153, 153, 255));
        jComboBox1.setFont(new java.awt.Font("TimeBurner", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Galego", "Español", "Português", "English", "Deutsch", "Italiano" }));
        jComboBox1.setBorder(null);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barraHorizontal.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barraHorizontal.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barraHorizontal.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/infoQR.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/telefonoAC.png"))); // NOI18N

        jLabel17.setBackground(new java.awt.Color(153, 153, 255));
        jLabel17.setFont(new java.awt.Font("TimeBurner", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Enquisa");

        jLabel18.setBackground(new java.awt.Color(153, 153, 255));
        jLabel18.setFont(new java.awt.Font("TimeBurner", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Informar dunha avería");

        jLabel19.setBackground(new java.awt.Color(153, 153, 255));
        jLabel19.setFont(new java.awt.Font("TimeBurner", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Axuda");

        jLabel6.setBackground(new java.awt.Color(153, 153, 255));
        jLabel6.setFont(new java.awt.Font("TimeBurner", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Detalles :");

        botonFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonFinalizar.png"))); // NOI18N
        botonFinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonFinalizarMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/textoReservaCompletada.png"))); // NOI18N

        jLabel7.setBackground(new java.awt.Color(153, 153, 255));
        jLabel7.setFont(new java.awt.Font("TimeBurner", 0, 23)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Reserva formalizada con éxito");

        jLabel9.setBackground(new java.awt.Color(153, 153, 255));
        jLabel9.setFont(new java.awt.Font("TimeBurner", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cargos :");

        jLabel10.setBackground(new java.awt.Color(153, 153, 255));
        jLabel10.setFont(new java.awt.Font("TimeBurner", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Data e horario :");

        jLabel11.setBackground(new java.awt.Color(153, 153, 255));
        jLabel11.setFont(new java.awt.Font("TimeBurner", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Participantes :");

        campoData.setFont(new java.awt.Font("TimeBurner", 0, 16)); // NOI18N
        campoData.setForeground(new java.awt.Color(255, 255, 255));
        campoData.setEnabled(false);

        campoParticipante1.setFont(new java.awt.Font("TimeBurner", 0, 16)); // NOI18N
        campoParticipante1.setForeground(new java.awt.Color(255, 255, 255));
        campoParticipante1.setEnabled(false);

        campoParticipante2.setFont(new java.awt.Font("TimeBurner", 0, 16)); // NOI18N
        campoParticipante2.setForeground(new java.awt.Color(255, 255, 255));
        campoParticipante2.setEnabled(false);

        campoImporte2.setFont(new java.awt.Font("TimeBurner", 0, 16)); // NOI18N
        campoImporte2.setForeground(new java.awt.Color(255, 255, 255));
        campoImporte2.setEnabled(false);

        campoImporteTotal.setFont(new java.awt.Font("TimeBurner", 0, 16)); // NOI18N
        campoImporteTotal.setForeground(new java.awt.Color(255, 255, 255));
        campoImporteTotal.setEnabled(false);

        jLabel12.setBackground(new java.awt.Color(153, 153, 255));
        jLabel12.setFont(new java.awt.Font("TimeBurner", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("+");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barraHorizontal.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barraHorizontal.png"))); // NOI18N

        campoImporte1.setFont(new java.awt.Font("TimeBurner", 0, 16)); // NOI18N
        campoImporte1.setForeground(new java.awt.Color(255, 255, 255));
        campoImporte1.setEnabled(false);

        jLabel14.setBackground(new java.awt.Color(153, 153, 255));
        jLabel14.setFont(new java.awt.Font("TimeBurner", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("TOTAL :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(jLabel2)
                        .addGap(138, 138, 138)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(botonAtras)
                        .addGap(6, 6, 6)
                        .addComponent(botonHome)
                        .addGap(12, 12, 12)
                        .addComponent(botonPower))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel15)
                        .addGap(127, 127, 127)
                        .addComponent(jLabel16)
                        .addGap(130, 130, 130)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(audioOn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(566, 566, 566)
                        .addComponent(botonFinalizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(468, 468, 468)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(36, 36, 36))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(18, 18, 18)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoImporte2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoImporte1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(159, 159, 159)
                                                .addComponent(campoImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoParticipante2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoParticipante1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(27, 27, 27)
                                        .addComponent(campoData)))))))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(58, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(39, 39, 39)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(botonAtras))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(botonHome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(botonPower)))
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(campoParticipante2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoParticipante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel9)
                .addGap(3, 3, 3)
                .addComponent(campoImporte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(campoImporte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(63, 63, 63)
                .addComponent(botonFinalizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(6, 6, 6)
                        .addComponent(audioOn))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(187, 187, 187)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(613, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void audioOnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_audioOnMouseClicked
        // TODO add your handling code here:
        t.restart();        
        if(clicked) {
            audioOn.setIcon(iconoAudioOff);
            clicked = false;
        } else {
            audioOn.setIcon(iconoAudioOn);
            clicked = true;
        }
    }//GEN-LAST:event_audioOnMouseClicked

    private void botonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtrasMouseClicked
        // TODO add your handling code here:               
        Object[] opcions = {"Si", "Non"};
        int resposta = JOptionPane.showOptionDialog(this,
                       "Seguro que quere saír? Se sae agora perderase a información cuberta",
                       "Cancelar proceso de reserva",
                       JOptionPane.YES_NO_CANCEL_OPTION,
                       JOptionPane.WARNING_MESSAGE,
                       null,
                       opcions,
                       null);

        if (resposta == JOptionPane.YES_OPTION) {
            t.stop();
            d.reseteaActividades();
            this.v.getContentPane().setVisible(false);
            PanelMain pm = new PanelMain(d);
            pm.setVisible(true);
            pm.setV(this.v);
            this.v.setContentPane(pm);
        }          
    }//GEN-LAST:event_botonAtrasMouseClicked

    private void botonHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonHomeMouseClicked
        // TODO add your handling code here:
        Object[] opcions = {"Si", "Non"};
        int resposta = JOptionPane.showOptionDialog(this,
                       "Seguro que quere saír? Se sae agora perderase a información cuberta",
                       "Cancelar proceso de reserva",
                       JOptionPane.YES_NO_CANCEL_OPTION,
                       JOptionPane.WARNING_MESSAGE,
                       null,
                       opcions,
                       null);

        if (resposta == JOptionPane.YES_OPTION) {
            t.stop();
            d.reseteaActividades();
            this.v.getContentPane().setVisible(false);
            PanelMain pm = new PanelMain(d);
            pm.setVisible(true);
            pm.setV(this.v);
            this.v.setContentPane(pm);
        }                  
    }//GEN-LAST:event_botonHomeMouseClicked

    private void botonPowerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPowerMouseClicked
        // TODO add your handling code here:
        Object[] opcions = {"Si", "Non"};
        int resposta = JOptionPane.showOptionDialog(this,
                       "Seguro que quere saír? Se sae agora perderase a información cuberta",
                       "Cancelar proceso de reserva",
                       JOptionPane.YES_NO_CANCEL_OPTION,
                       JOptionPane.WARNING_MESSAGE,
                       null,
                       opcions,
                       null);

        if (resposta == JOptionPane.YES_OPTION) {
            t.stop();
            d.reseteaActividades();
            this.v.getContentPane().setVisible(false);
            PanelInactive pi = new PanelInactive(d);
            pi.setVisible(true);
            pi.setV(this.v);
            this.v.setContentPane(pi);
        }               
    }//GEN-LAST:event_botonPowerMouseClicked

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        // TODO add your handling code here:
        Object[] opcions = {"Si", "Non"};
        int resposta = JOptionPane.showOptionDialog(this,
                       "Seguro que quere saír? Se sae agora perderase a información cuberta",
                       "Cancelar proceso de reserva",
                       JOptionPane.YES_NO_CANCEL_OPTION,
                       JOptionPane.WARNING_MESSAGE,
                       null,
                       opcions,
                       null);

        if (resposta == JOptionPane.YES_OPTION) {
            t.stop();
            d.reseteaActividades();
            this.v.getContentPane().setVisible(false);
            PanelMain pm = new PanelMain(d);
            pm.setVisible(true);
            pm.setV(this.v);
            this.v.setContentPane(pm);
        }                  
    }//GEN-LAST:event_logoMouseClicked

    private void botonFinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonFinalizarMouseClicked
        // TODO add your handling code here:
        t.stop();        
        d.reseteaActividades(); 
        this.v.getContentPane().setVisible(false);
        PanelMain pm = new PanelMain(d);
        pm.setVisible(true);
        pm.setV(this.v);
        this.v.setContentPane(pm); 
    }//GEN-LAST:event_botonFinalizarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel audioOn;
    private javax.swing.JLabel botonAtras;
    private javax.swing.JLabel botonFinalizar;
    private javax.swing.JLabel botonHome;
    private javax.swing.JLabel botonPower;
    private javax.swing.JTextField campoData;
    private javax.swing.JTextField campoImporte1;
    private javax.swing.JTextField campoImporte2;
    private javax.swing.JTextField campoImporteTotal;
    private javax.swing.JTextField campoParticipante1;
    private javax.swing.JTextField campoParticipante2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
