/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Pablo Rey
 */
public class PanelIDMenu extends javax.swing.JPanel {

    /**
     * Creates new form PanelInicial
     */
    private Ventana v;
    private Timer t;
    private DatosReserva d;
    
    private final ImageIcon iconoAudioOn;
    private final ImageIcon iconoAudioOff;
    URL urlAudioOn = PanelIDMenu.class.getResource("/img/audioOn.png");
    URL urlAudioOff = PanelIDMenu.class.getResource("/img/audioOff.png");
    boolean clicked = true;    
    
    public Ventana getV() {
        return v;
    }

    public void setV(Ventana v) {
        this.v = v;
    }
    
    public PanelIDMenu(DatosReserva d) {
        initComponents();
        
        // Declaramos las variables para los iconos de los altavoces
        // e iniciamos el contador de tiempo de inactividad
        iconoAudioOn = new javax.swing.ImageIcon(urlAudioOn);
        iconoAudioOff = new javax.swing.ImageIcon(urlAudioOff);        
        
        int tiempoEspera = 4 * 60 * 1000;
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                v.getContentPane().setVisible(false);
                PanelInactive pi = new PanelInactive(d);
                pi.setVisible(true);
                pi.setV(v);
                v.setContentPane(pi);                 
            }
        };
        t = new Timer(tiempoEspera, taskPerformer);
        t.start();   
        
        if(d != null)
            this.d = d;         
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        audioOn = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        botonHome = new javax.swing.JLabel();
        botonPower = new javax.swing.JLabel();
        botonAtras = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonInsertaTarxeta = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setMaximumSize(new java.awt.Dimension(1280, 800));
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setPreferredSize(new java.awt.Dimension(1280, 800));

        audioOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/audioOn.png"))); // NOI18N
        audioOn.setToolTipText("Activa o desactiva la asistencia por voz");
        audioOn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        audioOn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                audioOnMouseClicked(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });

        botonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        botonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonHomeMouseClicked(evt);
            }
        });

        botonPower.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/power.png"))); // NOI18N
        botonPower.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPowerMouseClicked(evt);
            }
        });

        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return.png"))); // NOI18N
        botonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAtrasMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(153, 153, 255));
        jLabel2.setFont(new java.awt.Font("TimeBurner", 0, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("martes 15 de novembro de 2016, 13:45");

        jComboBox1.setBackground(new java.awt.Color(153, 153, 255));
        jComboBox1.setFont(new java.awt.Font("TimeBurner", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Galego", "Español", "Português", "English", "Deutsch", "Italiano" }));
        jComboBox1.setBorder(null);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barraHorizontal.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barraHorizontal.png"))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(153, 153, 255));
        jLabel5.setFont(new java.awt.Font("TimeBurner", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Por favor, achegue a súa tarxeta ao lector situado na parte frontal do quiosco para tramitar a reserva:");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barraHorizontal.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/infoQR.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/telefonoAC.png"))); // NOI18N

        jLabel17.setBackground(new java.awt.Color(153, 153, 255));
        jLabel17.setFont(new java.awt.Font("TimeBurner", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Enquisa");

        jLabel18.setBackground(new java.awt.Color(153, 153, 255));
        jLabel18.setFont(new java.awt.Font("TimeBurner", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Informar dunha avería");

        jLabel19.setBackground(new java.awt.Color(153, 153, 255));
        jLabel19.setFont(new java.awt.Font("TimeBurner", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Axuda");

        jLabel6.setBackground(new java.awt.Color(153, 153, 255));
        jLabel6.setFont(new java.awt.Font("TimeBurner", 0, 23)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Identificación");

        botonInsertaTarxeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cardReading.png"))); // NOI18N
        botonInsertaTarxeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInsertaTarxetaMouseClicked(evt);
            }
        });

        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonCancelar.png"))); // NOI18N
        botonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(185, 185, 185))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(botonInsertaTarxeta)
                .addGap(361, 361, 361))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(jLabel2)
                        .addGap(138, 138, 138)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(botonAtras)
                        .addGap(6, 6, 6)
                        .addComponent(botonHome)
                        .addGap(12, 12, 12)
                        .addComponent(botonPower))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel15)
                        .addGap(127, 127, 127)
                        .addComponent(jLabel16)
                        .addGap(130, 130, 130)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(audioOn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(575, 575, 575)
                        .addComponent(botonCancelar)))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(565, 565, 565))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(botonAtras))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(botonHome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(botonPower)))
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(42, 42, 42)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addComponent(botonInsertaTarxeta)
                .addGap(27, 27, 27)
                .addComponent(botonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(6, 6, 6)
                        .addComponent(audioOn))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void audioOnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_audioOnMouseClicked
        // TODO add your handling code here:
        t.restart();         
        if(clicked) {
            audioOn.setIcon(iconoAudioOff);
            clicked = false;
        } else {
            audioOn.setIcon(iconoAudioOn);
            clicked = true;
        }       
    }//GEN-LAST:event_audioOnMouseClicked

    private void botonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtrasMouseClicked
        // TODO add your handling code here:
        t.stop();        
        this.v.getContentPane().setVisible(false);
        PanelCircuitos pc = new PanelCircuitos(d);
        pc.setVisible(true);
        pc.setV(this.v);
        this.v.setContentPane(pc);         
    }//GEN-LAST:event_botonAtrasMouseClicked

    private void botonHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonHomeMouseClicked
        // TODO add your handling code here:
        t.stop();        
        this.v.getContentPane().setVisible(false);
        PanelMain pm = new PanelMain(d);
        pm.setVisible(true);
        pm.setV(this.v);
        this.v.setContentPane(pm);    
    }//GEN-LAST:event_botonHomeMouseClicked

    private void botonPowerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPowerMouseClicked
        // TODO add your handling code here:
        t.stop();              
        this.v.getContentPane().setVisible(false);
        PanelInactive pi = new PanelInactive(d);
        pi.setVisible(true);
        pi.setV(this.v);
        this.v.setContentPane(pi);    
    }//GEN-LAST:event_botonPowerMouseClicked

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        // TODO add your handling code here:
        t.stop();           
        this.v.getContentPane().setVisible(false);
        PanelMain pm = new PanelMain(d);
        pm.setVisible(true);
        pm.setV(this.v);
        this.v.setContentPane(pm);        
    }//GEN-LAST:event_logoMouseClicked

    private void botonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMouseClicked
        // TODO add your handling code here:
        t.stop();           
        this.v.getContentPane().setVisible(false);
        PanelMenu pm = new PanelMenu(d);
        pm.setVisible(true);
        pm.setV(this.v);
        this.v.setContentPane(pm);       
    }//GEN-LAST:event_botonCancelarMouseClicked

    private void botonInsertaTarxetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInsertaTarxetaMouseClicked
        // TODO add your handling code here:
        t.stop();               
        this.v.getContentPane().setVisible(false);
        PanelReservaMenu prm = new PanelReservaMenu(d);
        prm.setVisible(true);
        prm.setV(this.v);
        this.v.setContentPane(prm);   
    }//GEN-LAST:event_botonInsertaTarxetaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel audioOn;
    private javax.swing.JLabel botonAtras;
    private javax.swing.JLabel botonCancelar;
    private javax.swing.JLabel botonHome;
    private javax.swing.JLabel botonInsertaTarxeta;
    private javax.swing.JLabel botonPower;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
