/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Pablo Rey
 */
public class PanelReservaRio extends javax.swing.JPanel {

    /**
     * Creates new form PanelInicial
     */
    private Ventana v;
    private Timer t;
    DecimalFormat formato;    
    float cantidad;
    private DatosReserva d;
    
    private final ImageIcon iconoAudioOn;
    private final ImageIcon iconoAudioOff;
    URL urlAudioOn = PanelReservaRio.class.getResource("/img/audioOn.png");
    URL urlAudioOff = PanelReservaRio.class.getResource("/img/audioOff.png");
    boolean clicked = true;    
    
    public Ventana getV() {
        return v;
    }

    public void setV(Ventana v) {
        this.v = v;
    }
    
    public PanelReservaRio(DatosReserva d) {
        initComponents();
        
        // Declaramos las variables para los iconos de los altavoces
        // e iniciamos el contador de tiempo de inactividad
        iconoAudioOn = new javax.swing.ImageIcon(urlAudioOn);
        iconoAudioOff = new javax.swing.ImageIcon(urlAudioOff);        
        
        int tiempoEspera = 4 * 60 * 1000;
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                v.getContentPane().setVisible(false);
                PanelInactive pi = new PanelInactive(d);
                pi.setVisible(true);
                pi.setV(v);
                v.setContentPane(pi);                 
            }
        };
        t = new Timer(tiempoEspera, taskPerformer);
        t.start();        
        
        formato = new DecimalFormat("0.00");
        cantidad = 0;
        
        if(d!=null)
            this.d = d;
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        audioOn = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        botonHome = new javax.swing.JLabel();
        botonPower = new javax.swing.JLabel();
        botonAtras = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        campoData = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        selector2 = new javax.swing.JCheckBox();
        selector1 = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        importe = new javax.swing.JTextField();
        botonReservar = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JLabel();
        boton11 = new javax.swing.JRadioButton();
        boton12 = new javax.swing.JRadioButton();
        boton13 = new javax.swing.JRadioButton();
        boton23 = new javax.swing.JRadioButton();
        boton21 = new javax.swing.JRadioButton();
        boton22 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(153, 153, 255));
        setMaximumSize(new java.awt.Dimension(1280, 800));
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setPreferredSize(new java.awt.Dimension(1280, 800));

        audioOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/audioOn.png"))); // NOI18N
        audioOn.setToolTipText("Activa o desactiva la asistencia por voz");
        audioOn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        audioOn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                audioOnMouseClicked(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });

        botonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        botonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonHomeMouseClicked(evt);
            }
        });

        botonPower.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/power.png"))); // NOI18N
        botonPower.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPowerMouseClicked(evt);
            }
        });

        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return.png"))); // NOI18N
        botonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAtrasMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(153, 153, 255));
        jLabel2.setFont(new java.awt.Font("TimeBurner", 0, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("martes 15 de novembro de 2016, 13:45");

        jComboBox1.setBackground(new java.awt.Color(153, 153, 255));
        jComboBox1.setFont(new java.awt.Font("TimeBurner", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Galego", "Español", "Português", "English", "Deutsch", "Italiano" }));
        jComboBox1.setBorder(null);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barraHorizontal.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barraHorizontal.png"))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(153, 153, 255));
        jLabel5.setFont(new java.awt.Font("TimeBurner", 0, 23)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Oferta temporal: Visita guiada polos viñedos do canón");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoMapa.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoRutas.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barraHorizontal.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoReservas.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoEventos.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoDeportes.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoOferta.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoRestaurante.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoAboutUs.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/infoQR.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/telefonoAC.png"))); // NOI18N

        jLabel17.setBackground(new java.awt.Color(153, 153, 255));
        jLabel17.setFont(new java.awt.Font("TimeBurner", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Enquisa");

        jLabel18.setBackground(new java.awt.Color(153, 153, 255));
        jLabel18.setFont(new java.awt.Font("TimeBurner", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Informar dunha avería");

        jLabel19.setBackground(new java.awt.Color(153, 153, 255));
        jLabel19.setFont(new java.awt.Font("TimeBurner", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Axuda");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fotoRio.png"))); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/textoReservaRio.png"))); // NOI18N

        jLabel22.setBackground(new java.awt.Color(153, 153, 255));
        jLabel22.setFont(new java.awt.Font("TimeBurner", 0, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Por favor, encha todos os campos :");

        campoData.setBackground(new java.awt.Color(153, 153, 255));
        campoData.setFont(new java.awt.Font("TimeBurner", 0, 13)); // NOI18N
        campoData.setForeground(new java.awt.Color(255, 255, 255));
        campoData.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "venres, 18 de novembro de 2016", "martes, 22 de novembro de 2016", "venres, 25 de novembro de 2016", "martes, 29 de novembro de 2016", "venres, 2 de decembro de 2016", "martes, 6 de decembro de 2016", "venres, 9 de decembro de 2016", "martes, 13 de decembro de 2016", "venres, 16 de decembro de 2016", "martes, 20 de decembro de 2016" }));
        campoData.setBorder(null);
        campoData.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel23.setBackground(new java.awt.Color(153, 153, 255));
        jLabel23.setFont(new java.awt.Font("TimeBurner", 1, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Participantes");

        jLabel24.setBackground(new java.awt.Color(153, 153, 255));
        jLabel24.setFont(new java.awt.Font("TimeBurner", 1, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Data :");

        jLabel25.setBackground(new java.awt.Color(153, 153, 255));
        jLabel25.setFont(new java.awt.Font("TimeBurner", 0, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("(marcar mínimo un) :");

        selector2.setFont(new java.awt.Font("TimeBurner", 1, 18)); // NOI18N
        selector2.setForeground(new java.awt.Color(255, 255, 255));
        selector2.setText("32524624P: Álvaro Gutiérrez Rodarte");
        selector2.setEnabled(false);

        selector1.setFont(new java.awt.Font("TimeBurner", 1, 18)); // NOI18N
        selector1.setForeground(new java.awt.Color(255, 255, 255));
        selector1.setText("22332233D: Bárbara Pelayo Aguirre");
        selector1.setEnabled(false);

        jLabel26.setBackground(new java.awt.Color(153, 153, 255));
        jLabel26.setFont(new java.awt.Font("TimeBurner", 1, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Importe :");

        importe.setFont(new java.awt.Font("TimeBurner", 0, 16)); // NOI18N
        importe.setForeground(new java.awt.Color(255, 255, 255));
        importe.setText("0,00 €");
        importe.setEnabled(false);

        botonReservar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonConfirmar.png"))); // NOI18N
        botonReservar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonReservarMouseClicked(evt);
            }
        });

        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonCancelar.png"))); // NOI18N
        botonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCancelarMouseClicked(evt);
            }
        });

        boton11.setFont(new java.awt.Font("TimeBurner", 0, 18)); // NOI18N
        boton11.setForeground(new java.awt.Color(255, 255, 255));
        boton11.setText("Paseo en catamarán (4 horas, sen experiencia, 14 €/persoa)");
        boton11.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boton11ItemStateChanged(evt);
            }
        });

        boton12.setFont(new java.awt.Font("TimeBurner", 0, 18)); // NOI18N
        boton12.setForeground(new java.awt.Color(255, 255, 255));
        boton12.setText("Rafting (2 horas, sen experiencia, 30 €/persoa)");
        boton12.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boton12ItemStateChanged(evt);
            }
        });

        boton13.setFont(new java.awt.Font("TimeBurner", 0, 18)); // NOI18N
        boton13.setForeground(new java.awt.Color(255, 255, 255));
        boton13.setText("Descenso en piragua (require experiencia, 45 €/persoa)");
        boton13.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boton13ItemStateChanged(evt);
            }
        });

        boton23.setFont(new java.awt.Font("TimeBurner", 0, 18)); // NOI18N
        boton23.setForeground(new java.awt.Color(255, 255, 255));
        boton23.setText("Descenso en piragua (require experiencia, 45 €/persoa)");
        boton23.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boton23ItemStateChanged(evt);
            }
        });

        boton21.setFont(new java.awt.Font("TimeBurner", 0, 18)); // NOI18N
        boton21.setForeground(new java.awt.Color(255, 255, 255));
        boton21.setText("Paseo en catamarán (4 horas, sen experiencia, 14 €/persoa)");
        boton21.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boton21ItemStateChanged(evt);
            }
        });

        boton22.setFont(new java.awt.Font("TimeBurner", 0, 18)); // NOI18N
        boton22.setForeground(new java.awt.Color(255, 255, 255));
        boton22.setText("Rafting (2 horas, sen experiencia, 30 €/persoa)");
        boton22.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boton22ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(jLabel2)
                        .addGap(138, 138, 138)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonHome)
                        .addGap(12, 12, 12)
                        .addComponent(botonPower))
                    .addComponent(jLabel1))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(127, 127, 127)
                                .addComponent(jLabel16)
                                .addGap(130, 130, 130)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(297, 297, 297)
                                        .addComponent(audioOn))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel19))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel22))
                                            .addComponent(jLabel21)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(182, 182, 182)
                                        .addComponent(botonReservar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonCancelar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel23)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel25))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel24)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(selector1)
                                            .addComponent(selector2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(boton12)
                                                    .addComponent(boton11)
                                                    .addComponent(boton13)
                                                    .addComponent(boton22)
                                                    .addComponent(boton21)
                                                    .addComponent(boton23)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(240, 240, 240)
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(importe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(botonPower))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAtras)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonHome))))
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(293, 293, 293)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(2, 2, 2)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel11)))
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selector1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selector2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(importe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonCancelar)
                            .addComponent(botonReservar))))
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(audioOn))
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(0, 4, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void audioOnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_audioOnMouseClicked
        // TODO add your handling code here:
        t.restart();
        if(clicked) {
            audioOn.setIcon(iconoAudioOff);
            clicked = false;
        } else {
            audioOn.setIcon(iconoAudioOn);
            clicked = true;
        }
    }//GEN-LAST:event_audioOnMouseClicked

    private void botonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtrasMouseClicked
        // TODO add your handling code here:
        Object[] opcions = {"Si", "Non"};
        int resposta = JOptionPane.showOptionDialog(this,
                       "Seguro que quere saír? Se sae agora perderase a información cuberta",
                       "Cancelar proceso de reserva",
                       JOptionPane.YES_NO_CANCEL_OPTION,
                       JOptionPane.WARNING_MESSAGE,
                       null,
                       opcions,
                       null);

        if (resposta == JOptionPane.YES_OPTION) {
            t.stop();
            this.v.getContentPane().setVisible(false);
            PanelMain pm = new PanelMain(d);
            pm.setVisible(true);
            pm.setV(this.v);
            this.v.setContentPane(pm);    
        }
        else {
            t.restart();
        }   
    }//GEN-LAST:event_botonAtrasMouseClicked

    private void botonHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonHomeMouseClicked
        // TODO add your handling code here:
        Object[] opcions = {"Si", "Non"};
        int resposta = JOptionPane.showOptionDialog(this,
                       "Seguro que quere saír? Se sae agora perderase a información cuberta",
                       "Cancelar proceso de reserva",
                       JOptionPane.YES_NO_CANCEL_OPTION,
                       JOptionPane.WARNING_MESSAGE,
                       null,
                       opcions,
                       null);

        if (resposta == JOptionPane.YES_OPTION) {
            t.stop();
            this.v.getContentPane().setVisible(false);
            PanelMain pm = new PanelMain(d);
            pm.setVisible(true);
            pm.setV(this.v);
            this.v.setContentPane(pm);    
        }
        else {
            t.restart();
        }     
    }//GEN-LAST:event_botonHomeMouseClicked

    private void botonPowerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPowerMouseClicked
        // TODO add your handling code here:
        Object[] opcions = {"Si", "Non"};
        int resposta = JOptionPane.showOptionDialog(this,
                       "Seguro que quere saír? Se sae agora perderase a información cuberta",
                       "Cancelar proceso de reserva",
                       JOptionPane.YES_NO_CANCEL_OPTION,
                       JOptionPane.WARNING_MESSAGE,
                       null,
                       opcions,
                       null);

        if (resposta == JOptionPane.YES_OPTION) {
            t.stop();
            this.v.getContentPane().setVisible(false);
            PanelInactive pi = new PanelInactive(d);
            pi.setVisible(true);
            pi.setV(this.v);
            this.v.setContentPane(pi);    
        }
        else {
            t.restart();
        }         
    }//GEN-LAST:event_botonPowerMouseClicked

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        // TODO add your handling code here:
        Object[] opcions = {"Si", "Non"};
        int resposta = JOptionPane.showOptionDialog(this,
                       "Seguro que quere saír? Se sae agora perderase a información cuberta",
                       "Cancelar proceso de reserva",
                       JOptionPane.YES_NO_CANCEL_OPTION,
                       JOptionPane.WARNING_MESSAGE,
                       null,
                       opcions,
                       null);

        if (resposta == JOptionPane.YES_OPTION) {
            t.stop();
            this.v.getContentPane().setVisible(false);
            PanelMain pm = new PanelMain(d);
            pm.setVisible(true);
            pm.setV(this.v);
            this.v.setContentPane(pm);    
        }
        else {
            t.restart();
        }             
    }//GEN-LAST:event_logoMouseClicked

    private void botonReservarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReservarMouseClicked
        // Se polo menos un dos checkbox está marcado mostramos unha ventá
        // emerxente de confirmación. En caso contrario, mostra unha ventá
        // cunha mensaxe de erro
        if (selector1.isSelected() || selector2.isSelected()) {
            Object[] opcions = {"Si", "Non"};
            int resposta = JOptionPane.showOptionDialog(this,
                "Confirma que desexa formalizar a reserva con esta información?",
                "Confirmar proceso de reserva",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null,
                opcions,
                null);

            if (resposta == JOptionPane.YES_OPTION) {
                t.stop();
                
                // Obtemos a descrición e o custo das actividades elixidas polo primeiro usuario
                String desc = "";
                float cantidadeParcial = 0;
                if(boton11.isSelected()) {
                    if(boton12.isSelected() || boton13.isSelected())
                        desc += "Paseo + ";
                    else
                        desc += "Paseo";
                    cantidadeParcial += 14;
                }
                if(boton12.isSelected()){
                    if(boton13.isSelected())
                        desc += "Rafting + ";
                    else
                        desc += "Rafting";
                    cantidadeParcial += 30;                    
                }
                if(boton13.isSelected()){
                    desc += "Descenso";
                    cantidadeParcial += 45;                    
                }
                
                if(selector1.isSelected()) {
                    String data = campoData.getSelectedItem().toString();
                    Actividade a = new Actividade(data, desc, cantidadeParcial);
                    d.engadirActividade(d.getUsuario(0), a);
                }
                
                // Obtemos a descrición e o custo das actividades elixidas polo segundo usuario                  
                desc = "";
                cantidadeParcial = 0;              
                if(boton21.isSelected()) {
                    if(boton22.isSelected() || boton23.isSelected())
                        desc += "Paseo + ";
                    else
                        desc += "Paseo";
                    cantidadeParcial += 14;
                }
                if(boton22.isSelected()){
                    if(boton23.isSelected())
                        desc += "Rafting + ";
                    else
                        desc += "Rafting";
                    cantidadeParcial += 30;                    
                }
                if(boton23.isSelected()){
                    desc += "Descenso";
                    cantidadeParcial += 45;                    
                }                
                if(selector2.isSelected()) {
                    String data = campoData.getSelectedItem().toString();
                    Actividade a = new Actividade(data, desc, cantidadeParcial);
                    d.engadirActividade(d.getUsuario(1), a);
                }
                this.v.getContentPane().setVisible(false);
                PanelReservaCompletada prc = new PanelReservaCompletada(d);
                prc.setVisible(true);
                prc.setV(this.v);
                this.v.setContentPane(prc);
            }
            else {
                t.restart();
            }
        }
        else {
            t.restart();
            JOptionPane.showMessageDialog(this,
                "Debe marcar polo menos unha opción",
                "Erro",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonReservarMouseClicked

    private void botonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMouseClicked
        // TODO add your handling code here:
        Object[] opcions = {"Si", "Non"};
        int resposta = JOptionPane.showOptionDialog(this,
            "Seguro que quere saír? Se sae agora perderase a información cuberta",
            "Cancelar proceso de reserva",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.WARNING_MESSAGE,
            null,
            opcions,
            null);

        if (resposta == JOptionPane.YES_OPTION) {
            t.stop();
            this.v.getContentPane().setVisible(false);
            PanelMain pm = new PanelMain(d);
            pm.setVisible(true);
            pm.setV(this.v);
            this.v.setContentPane(pm);   
        }
        else {
            t.restart();
        }
    }//GEN-LAST:event_botonCancelarMouseClicked

    private void boton11ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boton11ItemStateChanged
        // TODO add your handling code here:
        if (!selector1.isSelected()) {
            selector1.setSelected(true);
        }
        if (boton11.isSelected()) {
            cantidad += 14;
        }
        else {
            cantidad -= 14;
        }
        if(!boton11.isSelected() && !boton12.isSelected() && !boton13.isSelected())
            selector1.setSelected(false);
            
        importe.setText(formato.format(cantidad) + " €");
        t.restart();        
    }//GEN-LAST:event_boton11ItemStateChanged

    private void boton12ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boton12ItemStateChanged
        // TODO add your handling code here:
        if (!selector1.isSelected()) {
            selector1.setSelected(true);
        }
        if (boton12.isSelected()) {
            cantidad += 30;
        }
        else {
            cantidad -= 30;
        }
        if(!boton11.isSelected() && !boton12.isSelected() && !boton13.isSelected())
            selector1.setSelected(false);
        
        importe.setText(formato.format(cantidad) + " €"); 
        t.restart();
    }//GEN-LAST:event_boton12ItemStateChanged

    private void boton13ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boton13ItemStateChanged
        // TODO add your handling code here:
        if (!selector1.isSelected()) {
            selector1.setSelected(true);
        }
        if (boton13.isSelected()) {
            cantidad += 45;
        }
        else {
            cantidad -= 45;
        }
        if(!boton11.isSelected() && !boton12.isSelected() && !boton13.isSelected())
            selector1.setSelected(false);
        
        importe.setText(formato.format(cantidad) + " €");        
        t.restart();        
    }//GEN-LAST:event_boton13ItemStateChanged

    private void boton21ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boton21ItemStateChanged
        // TODO add your handling code here:
        if (!selector2.isSelected()) {
            selector2.setSelected(true);
        }
        if (boton21.isSelected()) {
            cantidad += 14;
        }
        else {
            cantidad -= 14;
        }
        if(!boton21.isSelected() && !boton22.isSelected() && !boton23.isSelected())
            selector2.setSelected(false);
        
        importe.setText(formato.format(cantidad) + " €");       
        t.restart();       
    }//GEN-LAST:event_boton21ItemStateChanged

    private void boton22ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boton22ItemStateChanged
        // TODO add your handling code here:
        if (!selector2.isSelected()) {
            selector2.setSelected(true);
        }
        if (boton22.isSelected()) {
            cantidad += 30;
        }
        else {
            cantidad -= 30;
        }
        if(!boton21.isSelected() && !boton22.isSelected() && !boton23.isSelected())
            selector2.setSelected(false);
        
        importe.setText(formato.format(cantidad) + " €");   
        t.restart();       
    }//GEN-LAST:event_boton22ItemStateChanged

    private void boton23ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boton23ItemStateChanged
        // TODO add your handling code here:
        if (!selector2.isSelected()) {
            selector2.setSelected(true);
        }
        if (boton23.isSelected()) {
            cantidad += 45;
        }
        else {
            cantidad -= 45;
        }
        if(!boton21.isSelected() && !boton22.isSelected() && !boton23.isSelected())
            selector2.setSelected(false);
        
       importe.setText(formato.format(cantidad) + " €");        
        t.restart();       
    }//GEN-LAST:event_boton23ItemStateChanged

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        Object[] opcions = {"Si", "Non"};
        int resposta = JOptionPane.showOptionDialog(this,
                       "Seguro que quere saír? Se sae agora perderase a información cuberta",
                       "Cancelar proceso de reserva",
                       JOptionPane.YES_NO_CANCEL_OPTION,
                       JOptionPane.WARNING_MESSAGE,
                       null,
                       opcions,
                       null);

        if (resposta == JOptionPane.YES_OPTION) {
            t.stop();
            this.v.getContentPane().setVisible(false);
            PanelOfertas po = new PanelOfertas(d);
            po.setVisible(true);
            po.setV(this.v);
            this.v.setContentPane(po); 
        }
        else {
            t.restart();
        }                   
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        Object[] opcions = {"Si", "Non"};
        int resposta = JOptionPane.showOptionDialog(this,
            "Seguro que quere saír? Se sae agora perderase a información cuberta",
            "Cancelar proceso de reserva",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.WARNING_MESSAGE,
            null,
            opcions,
            null);

        if (resposta == JOptionPane.YES_OPTION) {
            t.stop();            
            this.v.getContentPane().setVisible(false);
            PanelIDReservas pir = new PanelIDReservas(d);
            pir.setVisible(true);
            pir.setV(this.v);
            this.v.setContentPane(pir);           
        }
        else {
            t.restart();
        }          
    }//GEN-LAST:event_jLabel9MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel audioOn;
    private javax.swing.JRadioButton boton11;
    private javax.swing.JRadioButton boton12;
    private javax.swing.JRadioButton boton13;
    private javax.swing.JRadioButton boton21;
    private javax.swing.JRadioButton boton22;
    private javax.swing.JRadioButton boton23;
    private javax.swing.JLabel botonAtras;
    private javax.swing.JLabel botonCancelar;
    private javax.swing.JLabel botonHome;
    private javax.swing.JLabel botonPower;
    private javax.swing.JLabel botonReservar;
    private javax.swing.JComboBox<String> campoData;
    private javax.swing.JTextField importe;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel logo;
    private javax.swing.JCheckBox selector1;
    private javax.swing.JCheckBox selector2;
    // End of variables declaration//GEN-END:variables
}
